[package]
name = "dyn-timeout"
version = "0.1.0"
edition = "2021"
license-file = "LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1"
anyhow = "1"
tokio = { version = "1.15.0", features = ["full", "macros"] }